### ISSUE TITLE
RuntimeError: shape '[64, 10]' is invalid for input of size 160

### ISSUE THREAD

**Issue by ChipsGuardian** [gsp-27/pytorch_Squeezenet#2]
when i use a batch-size of 64, an runtime error occurs when it will almost finish the firt epoch training:
Train Epoch: 1 [49344/50000 (99%)]	Loss: 1.619473
Train Epoch: 1 [49984/50000 (100%)]	Loss: 1.664685
Traceback (most recent call last):
  File "F:/paper_code/pytorch_Squeezenet/main.py", line 208, in <module>
    train_acc.append(train(i))
  File "F:/paper_code/pytorch_Squeezenet/main.py", line 126, in train
    scores = scores.view(args.batch_size, args.num_classes)
RuntimeError: shape '[64, 10]' is invalid for input of size 160

can anyone tell me what i should do?QAQ

**Comment by ChipsGuardian** [comment]
fool me i sovle it...

**Comment by sampamisra** [comment]
How you solved this???

**Comment by Kirito0816** [comment]
> fool me i sovle it...

Could u pls tell me ur method to solve it ? Thank you.
