### ISSUE TITLE
code error in main.py

### ISSUE THREAD

**Issue by Rukhmini** [gsp-27/pytorch_Squeezenet#3]
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
~\pytorch_Squeezenet-master\main.py in <module>
    204         fig2, ax2 = plt.subplots()
    205         train_acc, val_acc = list(), list()
--> 206         for i in xrange(1,args.epoch+1):
    207             train_acc.append(train(i))
    208             val_acc.append(val())

NameError: name 'xrange' is not defined

**Comment by gsp-27** [comment]
Fixed
